name: Front pipeline

on:
    push:
        branches: [main]

jobs:
    unit-test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install dependencies
              run: npm install

            - name: run unit tests
              run: npm run test
    
    Code-quality-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: install dependencies
              run: npm install

            - name: run unit tests
              run: npm run lint

# 1 : Test Job
# 2 : Build and push Job
# 3 : Deploy Job